export const LOAD_API_MODEL = 'LOAD_API_MODEL';
export const SELECT_OPERATION = 'SELECT_OPERATION';

export const SET_API_ABSOLUTE_URI = 'SET_API_ABSOLUTE_URI';
export const SET_API_ACTION = 'SET_API_ACTION';
export const SELECT_API_PARAM = 'SELECT_API_PARAM';
export const UNSELECT_API_PARAM = 'UNSELECT_API_PARAM';
export const CLEAR_API_PARAMS = 'CLEAR_API_PARAMS';

export const SET_API_RESULT = 'SET_API_RESULT';
export const CLEAR_API_RESULT = 'CLEAR_API_RESULT';

export const SET_API_PAYLOAD = 'SET_API_PAYLOAD';
export const CLEAR_API_PAYLOAD = 'CLEAR_API_PAYLOAD';

export const SET_API_RETURN_HEADERS = 'SET_API_RETURN_HEADERS';
export const CLEAR_API_RETURN_HEADERS = 'CLEAR_API_RETURN_HEADERS';

export const SET_API_SEGMENT_VARIABLE = 'SET_API_SEGMENT_VARIABLE';
export const CLEAR_API_SEGMENT_VARIABLES = 'CLEAR_API_SEGMENT_VARIABLES';
