export const LOAD_API_MODEL = 'LOAD_API_MODEL';
export const SELECT_OPERATION = 'SELECT_OPERATION';

export const SET_API_BASE_URI = 'SET_API_BASE_URI';
export const SET_API_RELATIVE_URI = 'SET_API_RELATIVE_URI';
export const SET_API_ACTION = 'SET_API_ACTION';
export const SET_API_RESULT_FORMAT = 'SET_API_RESULT_FORMAT';
export const SET_RESULTS_FORMAT = 'SET_RESULTS_FORMAT';
export const SELECT_API_PARAM = 'SELECT_API_PARAM';
export const UNSELECT_API_PARAM = 'UNSELECT_API_PARAM';
export const CLEAR_API_PARAMS = 'CLEAR_API_PARAMS';
